#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright (C) 2014-2015 Luca Giovenzana <luca@giovenzana.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import sys
import time
import signal
from optparse import OptionParser
try:
    from fabric.api import sudo, env, settings
    from fabric.state import output as fabric_output
    from fabric.state import connections
    from fabric.context_managers import quiet
    from fabric.network import disconnect_all
except ImportError:
    print """
ImportError: Seems that fabric is not installed!
             Try with `sudo pip install fabric`
"""
    sys.exit(1)
try:
    import yaml
except ImportError:
    print """
ImportError: Seems that PyYAML is not installed!
             Try with `sudo pip install pyyaml`
"""
    sys.exit(1)

# Luchizz library
from utils import (query_yes_no,
                   check_root,
                   print_splash,
                   is_installed,
                   etckeeper_commit)
from tasks import (setup_etckeeper,
                   luchizz_shell,
                   luchizz_scripts,
                   set_ssh_keys,
                   luchizz_motd,
                   set_gitconfig,
                   luchizz_gitconfig,
                   set_bash_git_prompt,
                   set_disable_backports,
                   set_disable_recommended,
                   fix_perl_locale,
                   install_packages)


__author__ = "Luca Giovenzana <luca@giovenzana.org>"
__date__ = "2016-11-04"
__version__ = "0.1.0-beta2"

# Luchizz script folder
LUCHIZZ_DIR = os.path.dirname(os.path.realpath(__file__))

# #### KNOWN ISSUES
# FIXME handle returncode 1 in case of NO answer to apt-get
# FIXME handle stdout/err redirection

original_sigint = signal.getsignal(signal.SIGINT)


# Handle CTRL-C interrupt nicely
def ctrl_c_handler(sig, frame):
    signal.signal(signal.SIGINT, original_sigint)
    print "\nCTRL-C pressed exiting.."
    if connections:
        try:
            etckeeper_commit("luchizz commit after CTRL-C has been pressed")
            disconnect_all()
        except:
            pass
    sys.exit(1)


def main():
    signal.signal(signal.SIGINT, ctrl_c_handler)

    parser = OptionParser("usage: luchizz.py --host hosts [options]",
                          version="luchizz {}".format(__version__))
    parser.add_option("-H", "--hosts", dest="HOSTS",
                      help="comma-separated list of hosts to operate on",
                      type='string', metavar="HOSTS")
    parser.add_option("-p", "--packages-file", dest="PKGS_FILE",
                      help="yaml file for the debian packages you want to "
                      "install via apt-get",
                      type='string', metavar="PKGS_FILE")
    parser.add_option("-d", "--debug", dest="DEBUG",
                      help="all output from fabric", action='store_true',
                      default=False)
    (options, args) = parser.parse_args()

    # Setting up the target hosts
    if options.HOSTS:
        env.host_string = options.HOSTS.split(',')[0]

    # Setting up the default path for the packages yaml
    if not options.PKGS_FILE:
        options.PKGS_FILE = os.path.join(LUCHIZZ_DIR, 'packages.yaml')
    # Make sure the package file exists
    if os.path.isfile(options.PKGS_FILE):
        # get the dictionary from the yaml file
        p = open(options.PKGS_FILE, 'r')
        packages = yaml.load(p.read())
        p.close()
    else:
        print "IOError: packages file not found {}".format(options.PKGS_FILE)
        sys.exit(1)

    # Setting up fabric output for debug
    # FIXME here there are problem with the overrided options context managers
    # needs to be always used probably
    if options.DEBUG:
        to_set = {'aborts': True,
                  'debug': True,
                  'running': True,
                  'status': True,
                  'stderr': True,
                  'stdout': True,
                  'user': True,
                  'warnings': True}
    # Setting up fabric output for normal usage
    else:
        to_set = {'aborts': True,
                  'debug': False,
                  'running': False,
                  'status': False,
                  'stderr': False,
                  'stdout': True,
                  'user': False,
                  'warnings': True}
    # Apply the dictionary structure to the output handler of fabric
    for key in to_set.keys():
        fabric_output[key] = to_set[key]

    print_splash(__version__)
    with quiet():
        check_root()
    print("\nReady to luchizz: {}?\n"
          "CTRL-C to abort\n".format(env.host_string))
    time.sleep(1)

    # Setup etckeeper
    if not is_installed('etckeeper'):
        if query_yes_no("SETUP: etckeeper to track changes in /etc "
                        "using git?", 'yes'):
            setup_etckeeper()

    # Luchizz the shell
    if query_yes_no("CONFIGURE: do you want to `luchizz` root and all users "
                    "with a home folder in /home?", 'yes'):
        with quiet():
            luchizz_shell()
        # If luchizz shell is applied a dedicated commit is applied
        # 127 return code is in case etckeeper is not installed won't fail
        with settings(ok_ret_codes=(0, 1, 127)), quiet():
            sudo('etckeeper commit -m "luchizzed shell"')

    # Install luchizz scripts
    if query_yes_no("INSTALL: luchizz scripts in /usr/local/bin?", 'yes'):
        with quiet():
            luchizz_scripts()

    # Copy ssh keys
    if query_yes_no("CONFIGURE: local ssh keys as authorized for "
                    "authentication?", 'yes'):
        with quiet():
            set_ssh_keys()

    # Install custom motd scripts
    if query_yes_no("CONFIGURE: do you want to customize the message of the"
                    " day (motd)?", 'yes'):
        with quiet():
            luchizz_motd()

    # Copy .gitconfig
    if os.path.isfile(os.path.join(os.getenv('HOME'), '.gitconfig')):
        if query_yes_no("COPY: .gitconfig file from the local user?",
                        'yes'):
            with quiet():
                set_gitconfig()

    if query_yes_no("CONFIGURE: do you want to luchizz the .gitconfig for the "
                    "current user?", 'yes'):
            with quiet():
                luchizz_gitconfig()

    if query_yes_no("INSTALL: bash-git-prompt extension in /usr/local/lib?",
                    'yes'):
            with quiet():
                set_bash_git_prompt()

    # Disable backports
    if query_yes_no("DISABLE: backports repositories?", 'yes'):
        with quiet():
            set_disable_backports()

    # Disable automatic installation of suggested and recommended packages
    if query_yes_no("DISABLE: automatic installation of recommended packages?",
                    'yes'):
        with quiet():
            set_disable_recommended()

    # Fix common perl locale error because LC_ALL is not set
    if query_yes_no("FIX: common locale perl error by setting LC_ALL "
                    "to en_US.UTF-8?",
                    'yes'):
        with quiet():
            fix_perl_locale()

    for pkg_section in packages.keys():
        if query_yes_no("INSTALL: {} packages?".format(pkg_section),
                        'yes'):
            install_packages(packages[pkg_section])

    etckeeper_commit("final luchizz commit")
    print "\nluchizz done"
    return 0


if __name__ == '__main__':
    main()
