#!/bin/sh
SEPARATOR="----------------------------------------------------"
echo $SEPARATOR
free -m | egrep "Mem|Swap" | awk '{printf "%-10s %10s %sMB/%sMB[%.2f%s]\n", $1," ", $3, $2, ($3/$2)*100, "%"}'
echo $SEPARATOR
df -h | egrep "/dev/" | egrep -v shm | awk '{printf "%-20s %5s/%s/%s[%s]\n", substr($6,0,20) ,$2,$3,$4,$5;}'
echo $SEPARATOR
dpkg -s "mdadm" >/dev/null 2>&1 && {
        RAIDINFO=`cat /proc/mdstat | egrep "md|blocks"`
        printf "$RAIDINFO\n"
        echo "$SEPARATOR"
    } 
dpkg -s "libvirt-bin" >/dev/null 2>&1 && {
        virsh list
    } 
dpkg -s "docker-engine" >/dev/null 2>&1 && {
        docker ps
    }
echo
